### ISSUE TITLE
Dataset download not working

### ISSUE THREAD

**Issue by b-turan** [rajpurkarlab/cheXlocalize#11]
Dear authors,

it seems that the cheXlocalize dataset cannot be downloaded from the link provided in the `README.md`. Can you confirm this and if so, could you please provide an alternative source or fix the database? 

Thanks in advance!

**Comment by asaporta** [comment]
Hello!

Thank you so much for letting us know! Is this the link you're using? https://stanfordaimi.azurewebsites.net/datasets/23c56a0d-15de-405b-87c8-99c30138950c

Have you tried logging in and then downloading? If so, could you maybe send a screenshot of the error, and then we'll look into it further!

Adriel

**Comment by b-turan** [comment]
Yes, that is the link. I have tried both, with and without login, but the dataset does not load even after a long period of time. Therefore, there is no error message that I can share. Besides, my internet connection is quite stable and fast, so this can't be the problem. 

Here, the loading page:

![loading_page](https://user-images.githubusercontent.com/45353745/196496659-b895f87b-4631-4b7f-8a93-fba0c196a0fb.png)

**Comment by asaporta** [comment]
If you click the Download button under "Export Dataset" on the lefthand side here:

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/10553217/196541401-6bfbcc94-9c7e-4073-9fc6-658ca734e71f.png">

Do you then see this registration pop up?

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/10553217/196541818-e399e560-33be-48ff-96c0-233958a51a3b.png">

You'll need to open "Accept Agreement of Terms here".

And then you should see a pop up like this?

<img width="609" alt="image" src="https://user-images.githubusercontent.com/10553217/196542304-769f737f-fa5e-46c9-b5cd-c2fcf7b3542f.png">

**Comment by b-turan** [comment]
Thank you for the detailed explanation! 

Unfortunately, the Firefox browser did not load the provided link properly, so I couldn't find the download button under "Export Dataset" (see image of my first reply). However, switching to Google-Chrome solved the issue.

Nonetheless, the beta-version of the stanfordaimi-azure website, where the download link is located, seems to be generally unstable, regardless of the browsers I've used. Perhaps it would be useful to include a note in the readme file for future users to try different browsers.

Anyway, thanks for the quick replies!

**Comment by asaporta** [comment]
Ahh, that's great advice, thanks @b-turan ! I just added more detailed instructions for downloading the dataset [here](https://github.com/rajpurkarlab/cheXlocalize/blob/master/download_instructions.md), in case it's helpful, and I also added your note about the browser issue. Thanks for letting us know!
