### ISSUE TITLE
Access to trained DenseNet121

### ISSUE THREAD

**Issue by simonschallmoser** [rajpurkarlab/cheXlocalize#15]
Hi everyone,

I just wanted to ask whether it would be possible to get access to the trained DenseNet121?

Cheers,
Simon

**Comment by asaporta** [comment]
Hi Simon!

Here's [a document](https://docs.google.com/document/d/1VRTanEmMpawPRFz9TGzjcn1qTOiTWbqNfhMBUOelnXk/edit?usp=sharing) that describes the model checkpoints and that in turn links to the folder with the model checkpoints.

Good luck!
Adriel
